# Generated by Django 3.1.2 on 2020-10-13 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.FloatField()),
                ('time', models.DurationField()),
                ('location', models.CharField(max_length=256)),
                ('weather', models.CharField(default='?', max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
