# Generated by Django 3.1.2 on 2020-10-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='weather',
            field=models.CharField(default='?', max_length=128),
        ),
    ]
