# Generated by Django 3.1.2 on 2020-10-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0002_weeklyreport'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('week_start', 'owner'), name='one_report_per_week_and_owner'),
        ),
    ]
