# Generated by Django 3.1.2 on 2020-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0003_auto_20201014_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='average_speed_kmph',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='total_distance_km',
            field=models.FloatField(default=0),
        ),
    ]
